// Configuration types
export type {
  AuthNAuthConfig,
  OAuthConfig,
  AuthConfig,
  TradingClientConfig,
  FulfillmentClientConfig,
  InventoryClientConfig,
  AccountClientConfig,
  TaxonomyClientConfig,
  ComplianceClientConfig,
  EbaySiteIdValue,
} from './config.js';

export {
  EbaySiteId,
  getTradingEndpoint,
  getFulfillmentEndpoint,
  getInventoryEndpoint,
  getAccountEndpoint,
  getTaxonomyEndpoint,
  getComplianceEndpoint,
} from './config.js';

// Trading types (Generated namespace excluded - import from types/trading directly)
export type {
  AckCodeType,
  BaseResponse,
  ErrorType,
  ErrorParameterType,
  AmountType,
  CategoryType,
  NameValueListType,
  ItemSpecificsType,
  ShippingServiceOptionsType,
  ShippingDetailsType,
  FeeType,
  FeesType,
  AddItemType,
  AddItemRequest,
  VerifyAddItemRequest,
  ReviseItemType,
  ReviseItemRequest,
  EndingReasonType,
  EndItemRequest,
  DetailLevelType,
  GetItemRequest,
  NotificationEnableType,
  ApplicationDeliveryPreferencesType,
  SetNotificationPreferencesRequest,
  PreferenceLevelType,
  GetNotificationPreferencesRequest,
  TokenStatusType,
  GetTokenStatusResponse,
  AddItemResponse,
  ReviseItemResponse,
  EndItemResponse,
  SellerType,
  ItemType,
  GetItemResponse,
  DeliveryURLDetailsType,
  ApplicationDeliveryPreferencesResponseType,
  UserDeliveryPreferenceArrayType,
  SetNotificationPreferencesResponse,
  GetNotificationPreferencesResponse,
} from './trading/index.js';

// Fulfillment types (Generated namespace excluded - import from types/fulfillment directly)
export type {
  OrderStatusType,
  PaymentStatusType,
  FulfillmentStatusType,
  Amount,
  Address,
  Contact,
  Buyer,
  LineItem,
  ShippingFulfillment,
  Order,
  OrderSearchResponse,
  CreateShipmentRequest,
  CreateShipmentResponse,
  ShippingCarrierCode,
} from './fulfillment/index.js';

export { ShippingCarriers } from './fulfillment/index.js';

// Inventory types (Generated namespace excluded - import from types/inventory directly)
export type {
  ConditionEnum,
  PackageType,
  WeightUnitOfMeasure,
  LengthUnitOfMeasure,
  Amount as InventoryAmount,
  Aspects,
  Product,
  Dimensions,
  Weight,
  PackageWeightAndSize,
  TimeDuration,
  AvailabilityDistribution,
  ShipToLocationAvailability,
  PickupAtLocationAvailability,
  Availability,
  InventoryItem,
  CreateOrReplaceInventoryItemRequest,
  InventoryItemsResponse,
  OfferStatusEnum,
  FormatType,
  MarketplaceIdEnum,
  ListingDurationEnum,
  PricingSummary,
  ShippingCostOverride,
  BestOffer,
  ListingPolicies,
  Tax,
  ListingDetails,
  Offer,
  CreateOfferRequest,
  CreateOfferResponse,
  UpdateOfferRequest,
  PublishOfferResponse,
  OffersResponse,
} from './inventory/index.js';

// Account types (Generated namespace excluded - import from types/account directly)
export type {
  TimeDuration as AccountTimeDuration,
  TimeDurationUnit,
  CategoryType as AccountCategoryType,
  ShippingOption,
  Amount as AccountAmount,
  FulfillmentPolicy,
  FulfillmentPolicyRequest,
  SetFulfillmentPolicyResponse,
  FulfillmentPoliciesResponse,
  PaymentPolicy,
  PaymentPolicyRequest,
  SetPaymentPolicyResponse,
  PaymentPoliciesResponse,
  ReturnPolicy,
  ReturnPolicyRequest,
  SetReturnPolicyResponse,
  ReturnPoliciesResponse,
  SellingPrivileges,
  SellingLimit,
} from './account/index.js';

// Taxonomy types (Generated namespace excluded - import from types/taxonomy directly)
export type {
  MarketplaceId,
  BaseCategoryTree,
  Category,
  CategoryTreeNode,
  CategoryTree,
  CategorySubtree,
  AncestorReference,
  CategorySuggestion,
  CategorySuggestionResponse,
  ExpiredCategory,
  ExpiredCategoriesResponse,
  AspectDataType,
  AspectMode,
  AspectUsage,
  ItemToAspectCardinality,
  ValueConstraint,
  AspectValue,
  AspectConstraint,
  Aspect,
  AspectMetadata,
  CategoryAspect,
  GetCategoriesAspectResponse,
  CompatibilityProperty,
  GetCompatibilityPropertiesResponse,
  CompatibilityPropertyValue,
  GetCompatibilityPropertyValuesResponse,
} from './taxonomy/index.js';

// Compliance types (Generated namespace excluded - import from types/compliance directly)
export type {
  ComplianceType,
  ComplianceState,
  MarketplaceId as ComplianceMarketplaceId,
  NameValueList as ComplianceNameValueList,
  VariationDetails,
  AspectRecommendations,
  ProductRecommendation,
  CorrectiveRecommendations,
  ComplianceDetail,
  ComplianceViolation,
  ComplianceSummaryInfo,
  ComplianceSummary,
  PagedComplianceViolationCollection,
} from './compliance/index.js';

// Notification types
export * from './notifications/index.js';
